# Generated by Django 4.1 on 2022-08-05 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='DeviceName',
            new_name='deviceName',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='Port',
            new_name='port',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='UserName',
            new_name='userName',
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.device')),
                ('userModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
