# Generated by Django 4.1 on 2022-08-05 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_rename_address_device_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdevice',
            old_name='deviceModel',
            new_name='device',
        ),
        migrations.RenameField(
            model_name='userdevice',
            old_name='userModel',
            new_name='user',
        ),
    ]
